import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { buildPortolano, digestGeometry } from '../lib/portolano.js'
import { decodeRingDegrees } from '../lib/codec.js'
import { emit } from '../lib/emit.js'

const generator = { name: 'portolani', version: '0.0.0-test' }
const source = { id: 'atoll', url: null, sha256: 'sha256:test', bytes: 1 }
const geojson = JSON.parse(
  await readFile(new URL('./fixtures/atoll.geojson', import.meta.url), 'utf8')
)

const build = (options) => buildPortolano({ geojson, source, options, generator })

test('the same input and knobs give a byte-identical document', () => {
  const a = build({ kind: 'lines' })
  const b = build({ kind: 'lines' })
  assert.equal(JSON.stringify(a), JSON.stringify(b))
  assert.equal(a.digest, b.digest)
})

test('nothing in a portolano records when it was generated', () => {
  // Reproducibility is the point of publishing the generator at all. A
  // timestamp would make every regeneration a diff.
  const text = JSON.stringify(build({ kind: 'lines' }))
  assert.doesNotMatch(text, /\d{4}-\d{2}-\d{2}T/)
  assert.doesNotMatch(text, /generatedAt|timestamp|date/i)
})

test('the digest covers the geometry and nothing else', () => {
  const portolano = build({ kind: 'lines' })
  assert.equal(portolano.digest, digestGeometry(portolano.geometry))
  const relabelled = { ...portolano, provenance: { ...portolano.provenance, note: 'x' } }
  assert.equal(digestGeometry(relabelled.geometry), portolano.digest)
})

test('a different tolerance gives a different digest', () => {
  assert.notEqual(build({ kind: 'lines' }).digest, build({ kind: 'lines', tolerance: 2 }).digest)
})

test('polygons keep their holes; lines flatten them', () => {
  const polygons = build({ kind: 'polygons' })
  assert.ok(Array.isArray(polygons.geometry[0]))
  assert.equal(polygons.geometry[0].length, 2, 'the ringed island keeps its hole')
  const lines = build({ kind: 'lines' })
  assert.equal(typeof lines.geometry[0], 'string')
})

test('min-extent drops the speck and keeps the island', () => {
  assert.equal(build({ kind: 'polygons' }).counts.shapes, 3)
  assert.equal(build({ kind: 'polygons', minExtent: 0 }).counts.shapes, 4)
})

test('every polygon ring comes back closed after a round trip', () => {
  const portolano = build({ kind: 'polygons' })
  for (const rings of portolano.geometry) {
    for (const ring of rings) {
      const points = decodeRingDegrees(ring, portolano.encoding.precision)
      assert.ok(points.length >= 4)
      assert.deepEqual(points[0], points[points.length - 1])
    }
  }
})

test('bounds are the bounds of what was actually emitted', () => {
  const portolano = build({ kind: 'lines', bbox: [-12, -2, 3, 2] })
  const [west, south, east, north] = portolano.bounds
  assert.ok(west >= -12 && east <= 3 && south >= -2 && north <= 2)
})

test('provenance carries the generator, the source and every knob', () => {
  const { provenance } = build({ kind: 'lines', tolerance: 0.5, precision: 2, minExtent: 3 })
  assert.deepEqual(provenance.generator, generator)
  assert.equal(provenance.source.sha256, 'sha256:test')
  assert.deepEqual(provenance.options, {
    kind: 'lines',
    tolerance: 0.5,
    precision: 2,
    minExtent: 3,
    bbox: null,
  })
})

test('an unknown kind is refused rather than guessed at', () => {
  assert.throws(() => build({ kind: 'blobs' }), /kind must be/)
})

test('the module emitters carry the same document and the same digest', () => {
  const portolano = build({ kind: 'lines' })
  for (const format of ['esm', 'cjs']) {
    const text = emit(portolano, { format })
    const json = text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1)
    const parsed = JSON.parse(json)
    assert.equal(parsed.digest, portolano.digest, format)
    assert.match(text, /^\/\/ Generated by portolani@/, format)
  }
})
