// The document is JSON; these are the wrappers for consumers that want it as
// a module rather than a file to fetch. The JSON is always the same bytes
// inside whichever wrapper -- an ESM portolano and a JSON portolano carry the
// same digest, so a stamp survives the choice of emitter.

export const FORMATS = ['json', 'esm', 'cjs']

function body(portolano, pretty) {
  return pretty ? JSON.stringify(portolano, null, 2) : JSON.stringify(portolano)
}

function banner(portolano) {
  const { generator, source, options } = portolano.provenance
  return [
    `// Generated by ${generator.name}@${generator.version} -- do not edit by hand.`,
    `// Source: ${source.url ?? source.id}${source.sha256 ? ` (${source.sha256})` : ''}`,
    `// Knobs: tolerance=${options.tolerance} precision=${options.precision}` +
      ` minExtent=${options.minExtent}${options.bbox ? ` bbox=${options.bbox.join(',')}` : ''}`,
    source.attribution ? `// ${source.attribution}` : null,
  ]
    .filter(Boolean)
    .join('\n')
}

export function emit(portolano, { format = 'json', pretty = false } = {}) {
  switch (format) {
    case 'json':
      return body(portolano, pretty) + '\n'
    case 'esm':
      return `${banner(portolano)}\nexport const PORTOLANO = ${body(portolano, pretty)}\nexport default PORTOLANO\n`
    case 'cjs':
      return `${banner(portolano)}\nmodule.exports = ${body(portolano, pretty)}\n`
    default:
      throw new Error(`unknown --format ${format}; expected one of ${FORMATS.join(', ')}`)
  }
}
