#!/usr/bin/env node
// Assembles the GitHub Pages demo into _site/: one full-detail portolano
// generated by this package's own programmatic API, the static page from
// demo/, and the unmodified library files the page imports, vendored so a
// plain static host can serve them. Needs the network once, to fetch the
// pinned Natural Earth source; everything else is local.
//
// The page's whole argument is that small files are enough, so the build
// fails rather than ship a site heavier than the budget the README claims.

import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { buildPortolano, emit, loadSource, resolveSource } from '../lib/index.js'

const root = fileURLToPath(new URL('..', import.meta.url))
const site = path.join(root, '_site')
const BUDGET = 100_000

// Full detail at the source's own scale: tolerance 0 keeps every point, and
// three decimals is finer than 110m data resolves. The browser derives every
// coarser level from this one file.
const OPTIONS = { kind: 'lines', tolerance: 0, precision: 3, minExtent: 1 }

const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'))
const source = resolveSource('ne_110m_coastline')
const { geojson, sha256, bytes } = await loadSource(source)
const portolano = buildPortolano({
  geojson,
  source: { ...source, sha256, bytes },
  options: OPTIONS,
  generator: { name: pkg.name, version: pkg.version },
})

await rm(site, { recursive: true, force: true })
await mkdir(path.join(site, 'vendor', 'portolani'), { recursive: true })
await writeFile(path.join(site, 'coast-full.json'), emit(portolano))
await cp(path.join(root, 'demo'), site, { recursive: true })
// Favicon and share-preview image: the same render the README already uses.
await cp(
  path.join(root, 'docs', 'the-world-in-8kb.svg'),
  path.join(site, 'the-world-in-8kb.svg')
)
for (const file of ['simplify.js', 'codec.js']) {
  await cp(path.join(root, 'lib', file), path.join(site, 'vendor', 'portolani', file))
}
await cp(
  path.join(root, 'node_modules', 'coast-wright', 'lib'),
  path.join(site, 'vendor', 'coast-wright'),
  { recursive: true }
)

async function weigh(dir, prefix = '') {
  let total = 0
  for (const entry of (await readdir(dir)).sort()) {
    const file = path.join(dir, entry)
    const info = await stat(file)
    if (info.isDirectory()) {
      total += await weigh(file, `${prefix}${entry}/`)
    } else {
      console.log(`${String(info.size).padStart(8)}  ${prefix}${entry}`)
      total += info.size
    }
  }
  return total
}

const total = await weigh(site)
console.log(`${String(total).padStart(8)}  total (budget ${BUDGET})`)
if (total > BUDGET) {
  console.error(`demo weighs ${total} bytes; the page about small files must stay under ${BUDGET}`)
  process.exit(1)
}
